### ISSUE TITLE
Forum role per membership level not set

### ISSUE THREAD

**Issue by ipokkel** [strangerstudios/pmpro-bbpress#29]
When the bbPress default forum role is set as "Participant" and setting a different forum role, e.g. "Spectator", on a membership level configuration page the user is still assigned the default bbPress "Participant" forum role after checkout instead of the forum role set for the membership level.

As a temporary workaround, adding this code to a customization plugin assigns the forum role set per level.
https://gist.github.com/pbrocks/36b3d84c075ec6d8a0a6b6f6edd15c00

**Comment by ideadude** [comment]
Looks like we added the option there, but never really coded the plugin to anything with that option. I can move in a version of that gist.

**Comment by ideadude** [comment]
Implemented here https://github.com/strangerstudios/pmpro-bbpress/commit/3c289e8ff89a70552a8059179180546a85203e35

Updated some functions in the plugin to support this.
Using the pmpro_after_change_membership_level hook instead of after checkout hook.
Using the bbp_set_role function instead of editing the capabilities directly.
Handles cancellations as well.
Ignores admins.

Should be updated for MMPU support (pick the 'highest' role of all the levels).

Should be tested a bit.

**Comment by andrewlimaza** [comment]
Tested this, it works now.

It won't work if you are editing the user via profile page as there's an onscreen dropdown for forum role and this will overwrite our automated things.

This also won't adjust admin's forum roles.

I do think we should support MMPU though.

**Comment by andrewlimaza** [comment]
However, I think you can only have one forum role anyway.

**Comment by andrewlimaza** [comment]
So we would need to choose the 'highest' level. Currently it'd pick the last processed level's role.

**Comment by andrewlimaza** [comment]
I'm going to close this ticket and mark it as resolved, I think we should have a gist to choose a specific role if a user has more than one level.
